version: '3.7'

services:
  web:
    build: 
      context: .
      dockerfile: ./infra/web/Dockerfile.dev
    ports:
      - 3000:3000
      - 3001:8000
    volumes:
      - ./app/web/cart-next:/home/node/app